<html><head><meta charset="utf-8" /><meta content="width=device-width, initial-scale=1.0" name="viewport" /><meta content="Caro Appleby" name="author" /><meta content="Musings on code and learning" name="description" /><title>Caro's Blog</title><link href="https://caro401.github.io/static/css/prism.css" rel="stylesheet" /><link href="https://caro401.github.io/static/css/firn_base.css" rel="stylesheet" /><script src="https://caro401.github.io/static/js/prism.js"></script></head><body><nav class="nav"><a class="nav-links-item" href="https://caro401.github.io/"><span>Home</span></a><a class="nav-links-item" href="https://caro401.github.io/about"><span>About</span></a><a class="nav-links-item" href="https://caro401.github.io/tags"><span>Tags</span></a></nav><main><article class="content"><h1>Testing Exceptions with Pytest</h1><p class="frontmatter">Created: 2020-08-02 Last updated: 2021-01-21</p><div><section><p><span>Every time I end up wanting to test that an expected exception is thrown with </span><a class="firn-external" href="https://docs.pytest.org/en/latest/assert.html#assertions-about-expected-exceptions" target="_blank">Pytest</a><span>, I end up looking up the syntax, so here it is:</span></p><pre class="language-python"><code class="language-python">import pytest

def test_my_exception_is_raised():
    with pytest.raises(MyException):
        my_function()
</code></pre><p><span>This test will fail if calling </span><code>my_function()</code><span> </span><em><span>doesn't</span></em><span> raise an exception of the type </span><code>MyException</code><span>.</span></p><p><span>But what if I want to check the exception has the expected message too?</span></p><pre class="language-python"><code class="language-python">def test_my_exception_is_raised_with_message():
    with pytest.raises(MyException) as e:
        my_function()
    assert "my message" in str(e.value)
</code></pre><p><span>In this case, </span><code>e</code><span> is of type </span><a class="firn-external" href="https://docs.pytest.org/en/stable/reference.html#exceptioninfo" target="_blank">ExceptionInfo</a><span>, not actually </span><code>Exception</code><span>, so you need to use </span><code>e.value</code><span> to get at the message. You can also assert things about the traceback of the exception via </span><code>e.traceback</code><span>, but I've not had a usecase for that recently.</span></p><p><span>While I was looking this stuff up again, I found out that you can actually clean this up a bit in some situations, by doing a regex match on the string representation of the exception thrown, like this:</span></p><pre class="language-python"><code class="language-python">def test_my_exception_is_raised():
    with pytest.raises(MyException, match=r"^My message.*"):
        my_function()
</code></pre><p><span>This uses </span><a class="firn-external" href="https://docs.python.org/3/library/re.html#re.Pattern.search" target="_blank">re.search</a><span> to do the matching, and see the </span><a class="firn-external" href="https://docs.python.org/3/library/re.html#regular-expression-syntax" target="_blank">Python docs</a><span> for a quick regex reference.</span></p><p><span>I think I'd use this regex method if I wanted to assert something like the presence of a particular error code somewhere in my error message, but the more verbose version when I'm asserting something about the message that depends on the context of my test, such as is the ID of the thing I just tried to put into my database in the error message.</span></p><pre class="language-python"><code class="language-python">def test_this_raises_error_code_1234():
    with pytest.raises(MyException, match=r"1234"):
        myfunction()

def test_this_raises_error_including_item_id_and_data():
    my_test_id, my_test_data = "XXXX", {"some": "data"}
    my_test_object = MyThing(id=my_test_id, data=my_test_data)

    with pytest.raises(MyException) as e:
        my_function(my_test_object)

    assert f"Couldn't process MyThing {my_test_id} with data {my_test_data}!" in str(e.value)
</code></pre></section></div></article></main></body></html>